#!/bin/sh -ex

# configure tkl-webcp
WEBROOT=/var/lib/tomcat7/webapps/ROOT

rm $WEBROOT/index.html

for dir in js css images; do
    mkdir -p $WEBROOT/$dir
    cp -a /var/www/$dir/* $WEBROOT/$dir
    rm -rf /var/www/$dir
done

sed -i "s|HOSTNAME_DESC|Tomcat|g" $WEBROOT/index.jsp
sed -i "s|HOSTNAME|tomcat|g" $WEBROOT/index.jsp

# allow binding to 80/443
sed -i "s/^#AUTHBIND.*/AUTHBIND=yes/" /etc/default/tomcat7
# from http://stackoverflow.com/a/23547702/3124333
touch /etc/authbind/byport/80
chmod 500 /etc/authbind/byport/80
chown tomcat7 /etc/authbind/byport/80
touch /etc/authbind/byport/443
chmod 500 /etc/authbind/byport/443
chown tomcat7 /etc/authbind/byport/443

# generate tomcat keystore from default ssl certificate
/usr/lib/inithooks/firstboot.d/16tomcat-sslcert

# from https://bugs.launchpad.net/ubuntu/+source/tomcat7/+bug/1232258
ln -s /var/lib/tomcat7/common/ /usr/share/tomcat7/common
ln -s /var/lib/tomcat7/server/ /usr/share/tomcat7/server
ln -s /var/lib/tomcat7/shared/ /usr/share/tomcat7/shared
ln -s /var/lib/tomcat7/conf/ /usr/share/tomcat7/conf
ln -s /var/lib/tomcat7/logs/ /usr/share/tomcat7/logs
